name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [closed]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # or 3.11, etc.

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r hls/requirements.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v1

        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and push energy-abnormal-simulator
      #   id: build_energy-abnormal-simulator
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./energy-abnormal-simulator
      #     file: ./energy-abnormal-simulator/Dockerfile
      #     push: true
      #     tags: nxthongbk/energy-abnormal:latest

      # - name: Build and push energy-always-abnormal
      #   id: build_energy-always-abnormal
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./energy-always-abnormal
      #     file: ./energy-always-abnormal/Dockerfile
      #     push: true
      #     tags: nxthongbk/energy-always-abnormal:latest
      - name: Build and push cms-simulator
        id: cms-simulator
        uses: docker/build-push-action@v2
        with:
          context: ./cms-simulator
          file: ./cms-simulator/Dockerfile
          push: true
          tags: nxthongbk/cms-simulator:latest
      